### ISSUE TITLE
Interest in extension of the tool?

### ISSUE THREAD

**Issue by Apanatshka** [BurntSushi/cargo-benchcmp#1]
I forked your project and ported it to Rust as an exercise. I don't consider that an improvement, since you now need to compile the tool before you can use it. So I didn't open a PR. Besides, it's in an orphan branch because it doesn't really relate strongly to the Python stuff. 

But then I had an idea to add to the tool and I did it to the Rust version because I'm more familiar with that code. Are you interested in pulling that code back into this repo? I prefer contributing/collaborating, even though it's a small tool.

**Comment by BurntSushi** [comment]
Ah that's awesome! I had been meaning to port it to Rust actually. Your port looks great! I'd love to pull in that to this repo.

It's true that it's a bummer that it needs to be compiled first, but I think this is exactly the kind of tool that should be installed with `cargo install`. :-)

**Comment by Apanatshka** [comment]
> [...] but I think this is exactly the kind of tool that should be installed with `cargo install`. :-)

That true :) 
I was planning to look into what I can do to make it install as a cargo command, and then open a PR. Or do you prefer to pull my changes in now and starting working on PR basis already?

**Comment by BurntSushi** [comment]
@Apanatshka I think what you have now is perfect. I'll put it up on crates.io. As long as the binary name is `cargo-benchcmp` and is in your `PATH`, then running `cargo benchcmp` will do the right thing.

**Comment by Apanatshka** [comment]
Ah, so that's how it works! I changed the usage string to no longer have the dash between cargo and benchcmp then. 
How do you want to pull the changes in? Shall I do a PR again the master branch, or do you want to move the python code away from the master branch first like I did, or is it easier for you to pull things in yourself without a PR, or ...?

**Comment by BurntSushi** [comment]
I think a PR against the master branch is just fine (which should indeed include removing the Python code).

**Comment by Apanatshka** [comment]
With #2 in place, I think we're done here :)

**Comment by BurntSushi** [comment]
Thanks @Apanatshka! I know I  left a lot of feedback on your code. If you're not up to a code review that's _totally OK_ and I'll be happy to merge anyway. Just let me know.

**Comment by Apanatshka** [comment]
I'm loving your code review ;) I have very limited experience with Rust, and the parts of the code are simply bad because I just wanted it to <del>work</del><ins>run</ins>, so I'm happily reading your feedback! I won't have time to act on your comments today, but I definitely will, so don't merge yet :)

**Comment by BurntSushi** [comment]
@Apanatshka Fantastic! The code is actually very nice overall. It was easy for me to review which is a really good thing!
