### ISSUE TITLE
(un)License issue

### ISSUE THREAD

**Issue by wimh** [BurntSushi/cargo-benchcmp#11]
I noticed this project is Dual-licensed under MIT or the UNLICENSE. That is very generous. However you seem to use crates which are not UNLICENSE'd. I believe that is a problem.

The UNLICENSE includes this text:

> Anyone is free to [...] distribute this software, either in source code
> form or as a compiled binary, [...]

There are no conditions to this distribution. Now look at prettytable-rs which uses a BSD license which includes:

>  Redistributions in binary form must reproduce the above copyright notice,
>  this list of conditions and the following disclaimer in the documentation
>  and/or other materials provided with the distribution.

This is not compatible. You are using prettytable-rs which requires a copyright notice in binary distributions, however the Unlicense allows distributions without copyright notice.

There is no issue with source-code distributions, because the source-code of cargo-benchcmp does not include the source-code of any of the crates it uses. There is also no issue to use a compiled binary, but it will be unredistributable. 

This also applies to regex, rustc-serialize and lazy-static.rs which are in the Cargo.toml too. 

I believe you should either drop the Unlicense, or stop using crates which do not use the Unlicense.

**Comment by BurntSushi** [comment]
There's no incompatibility because I'm not redistributing binaries. Any binary redistribution would just need to include all constituent licenses, which is true regardless of whether the UNLICENSE is used or not.

I'm not removing the UNLICENSE.
