### ISSUE TITLE
are colors backwards?

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/cargo-benchcmp#18]
While the colors look pretty, it feels like they are reversed. @Apanatshka was this intentional? In particular, red feels "bad" to me, but in fact, red is _good_ because it indicates a speedup. However, I can also see how red means "negative"...

**Comment by Apanatshka** [comment]
I did mean red to be "bad", aka a regression, but I messed up the definition of a regression [here](https://github.com/BurntSushi/cargo-benchcmp/pull/9/files#diff-639fbc4ef05b315af92b4d836c31b023R103) 😳 
I'll fix that right away.
