### ISSUE TITLE
write tests

### ISSUE THREAD

**Issue by BurntSushi** [BurntSushi/cargo-benchcmp#3]

**Comment by Apanatshka** [comment]
Did you have anything specific in mind here?

**Comment by BurntSushi** [comment]
Unit tests:
- Test the benchmark parser, including the fact that throughput is optional.
- Test that find overlap finds the correct pairs.
- Test that find overlap reports correct missing benchmarks (for both old and new).
- Test that the name determination for the two columns works correctly when given two file paths. (This may require refactoring the `names` method off of the `Args` struct.)
- Test `commafy`.

Integration tests:
- Test some basic example inputs and check that it produces the expected output.
- Test that the name prefix feature works. (Possibly also refactor code into a unit test.)
- Test that passing input on `stdin` works.

There may be others but this is all I've got off the top of my head at the moment. Bonus points if we can use quickcheck.

**Comment by Apanatshka** [comment]
Given #10 and #13, can we close this?

**Comment by BurntSushi** [comment]
Oh yes indeed! Thanks so much. :-)
